Version 1.1
Recognize 2 more states: full and unknown.

diff --git a/battery b/battery
--- a/battery
+++ b/battery
@@ -7,7 +7,7 @@
 #
 #     https://creativecommons.org/publicdomain/zero/1.0
 
-VERSION="1.0"
+VERSION="1.1"
 
 # SET ALIASES FOR SECURITY
 
@@ -26,8 +26,9 @@ Options:\n\
   -h, --help        Print this help.\n\
   -v, --version     Print this program's version.\n\
   -l, --list        List detected power supplies.\n\
-  --color=WHEN      Colorize the output; WHEN can be 'charging',\n\
-                    'discharging' (default), 'always', or 'never'.\n\
+  --color=WHEN      Colorize the output; WHEN can be either 'charging',\n\
+                    'discharging' (default), 'full', 'unknown', 'always', or\n\
+                    'never'.\n\
 \n\
 Examples:\n\
 \n\
@@ -46,6 +47,8 @@ Examples:\n\
     && exit 0
 
 [[ $1 == "-v" ]] || [[ $1 == "--version" ]] && echo $VERSION && exit 0
+[ $# -gt 2 ] && \
+    echo "Invalid number of arguments. Use '--help' for help." && exit 1
 
 # DETERMINE POWER SUPPLY
 
@@ -102,16 +105,20 @@ fi
 color=""  # Text color
 attr=""   # Text attribute
 
+# If --color is set to always or matches the battery $state, or the user did not
+# specify --color but the battery is discharging, the output is to be colorized,
+# so set the text color and text attribute according to the battery level.
 if [[ $1 == "--color=always" ]] || [[ $1 == "--color=${state,,}" ]] \
 || ( [[ ${1:0:1} != "-" ]] && [[ $state == "Discharging" ]] )
 then
-    [ $level -le 100 ] && color=32 && attr=1  # 76-100
-    [ $level -le 75 ] && attr=0               # 51-75
-    [ $level -le 50 ] && color=33 && attr=1   # 26-50
-    [ $level -le 25 ] && color=31 && attr=0   # 11-25
-    [ $level -le 10 ] && attr=1               # 1-10
+    [ $level -le 100 ] && color=32 && attr=1  # 76-100 (bold green)
+    [ $level -le 75 ] && attr=0               # 51-75 (normal green)
+    [ $level -le 50 ] && color=33 && attr=1   # 26-50 (bold yellow)
+    [ $level -le 25 ] && color=31 && attr=0   # 11-25 (normal red)
+    [ $level -le 10 ] && attr=1               # 1-10 (bold red)
 elif [[ ${1:0:1} == "-" ]] && [[ $1 != "--color=charging" ]] \
-  && [[ $1 != "--color=discharging" ]] && [[ $1 != "--color=never" ]]
+  && [[ $1 != "--color=discharging" ]] && [[ $1 != "--color=full" ]] \
+  && [[ $1 != "--color=unknown" ]] && [[ $1 != "--color=never" ]]
 then
     echo "Invalid option '$1'. Use '-h' for help."
     exit 1
